### ISSUE TITLE
Remove or fix 4.1.3

### ISSUE THREAD

**Issue by WarningImHack3r** [DesignThen/svelte-icons#52]
With your recent update to Svelte 5 in 36058f2, it seems like you've accidentally published it as 4.1.3 as well as 5.0.0.

It thus breaks everything with Dependabot and others, creating the need to avoid 4.1.3 in the version specifier. Can you please unpublish 4.1.3 if you can, or push 4.1.4 to revert that change?

**Comment by OllieJT** [comment]
Can't believe I'm only seeing this now. Apologies! This was also an ungraceful rename to @designthen/svelte-icons where I caught the issue and fixed it.

Thanks for reporting, and sorry I missed this when it mattered.

**Comment by WarningImHack3r** [comment]
No problem! What's the fix then? Will you push 4.1.4?
